// Define the RS485 network configuration
#define VNET_SUBNET			0xCE00	//USART Range
#define VNET_SUBNET_MASK	0xFF00

#define RS485_GATEWAY_ADDR			VNET_SUBNET | 0x0001
#define RS485_BUTTONS_PANEL_1_ADDR	VNET_SUBNET | 0x0002
#define RS485_RELAYS_1_ADDR			VNET_SUBNET | 0x0003

// BUTTONS_PANEL_1 Slots
#define BUTTONS_PANEL_1_BUTTON_1_SLOT			0
#define BUTTONS_PANEL_1_BUTTON_2_SLOT			1
#define BUTTONS_PANEL_1_LED_1_SLOT				2
#define BUTTONS_PANEL_1_LED_2_SLOT				3

// RELAYS_1 Slots
#define RELAYS_1_RELAY_1_SLOT					0
#define RELAYS_1_RELAY_2_SLOT					1

#define GATEWAY_LIGHT_1_SLOT					0
#define GATEWAY_LIGHT_2_SLOT					1
#define GATEWAY_BUTTONS_PANEL_1_BUTTON_1_SLOT	2
#define GATEWAY_BUTTONS_PANEL_1_BUTTON_2_SLOT	3
